Vagrant.configure("2") do |config|
  # config.vm.box = "fedora/29-cloud-base"
  config.vm.box = 'package.box'

  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = "workstation"

    v.memory = 2048
    v.cpus = 2

    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--memory", 2048]
  end

  # config.vm.network :private_network, ip: '192.168.2.2'
  # config.vm.synced_folder ".", "/vagrant", type: "nfs"

  # config.vm.provision "shell", path: "02-provision-network.sh", privileged: false
end